# Generated by Django 3.2.16 on 2022-10-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_equipousuario_fecha_entr'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='valido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipousuario',
            name='key_Equipo',
            field=models.ForeignKey(limit_choices_to={'valido': True}, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo'),
        ),
    ]
